[project]
name = "river-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "river-connectors",
    "river-databases",
]

[tool.uv.sources]
river-databases = { workspace = true }
river-connectors = { workspace = true }

[project.scripts]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
