# This file is for custom makefile targets at the project level.
# They are meant to be share by the whole project team.

## -- Project targets ----------------------------------------------------------------------------------------------- ##
.PHONY: info
info: ## Get project configuration info
	@echo ""
	@echo -e "$(_BLUE)--- Configuration Status ---$(_NORMAL)"
	@echo ""
	@echo -e "$(_CYAN)Application Name$(_NORMAL)         : $(APPLICATION_NAME)"
	@echo -e "$(_CYAN)Application version$(_NORMAL)      : $(APP_VERSION)"
	@echo -e "$(_CYAN)Project Root$(_NORMAL)             : [$(PROJECT_PATH)]"
	@echo -e "$(_CYAN)Applications$(_NORMAL)             : [$(PROJECT_PATH)apps/]"
	@echo -e "$(_CYAN)Packages$(_NORMAL)                 : [$(PROJECT_PATH)packages/]"
	@echo -e "$(_CYAN)Environment manager$(_NORMAL)      : $(DEFAULT_INSTALL_ENV)"
	@echo -e "$(_CYAN)Build tool$(_NORMAL)               : $(DEFAULT_BUILD_TOOL)"
	@echo -e "$(_CYAN)Python version$(_NORMAL)           : $(PYTHON_VERSION)"
	@echo -e "$(_CYAN)Active makefile targets$(_NORMAL)  : [$(TARGET_GROUPS)]"
	@echo -e "$(_CYAN)Makefile version$(_NORMAL)         : $(MAKEFILE_VERSION)"